#Faris alsubaie


#This dataset contains a list of video games with sales greater than 100,000 copies. 
#It was generated by a scrape of vgchartz.com.
library(dplyr)
library(tidyverse)


games <- read.csv("data/vgsales.csv")

#Exploratory Data Analysis

summary(games)
str(games)

NA_S <- games$NA_Sales
EU_S <- games$EU_Sales
JP_S <- games$JP_Sales
Other_S <- games$Other_Sales
